#!/bin/bash
string=$(lsof -t -i:$1)
if [ -z $string ]; then
	echo "No active processes on $1 found"
else
	processinfo=$(ps -p $string)
	printf "$processinfo \n"
	read -p "Do you want to kill this process on port $1? Y/N: " response
	case $response in
	"Y" | "y") kill -9 $string 
	echo "Killed $string, you heartless bastard.";;
	"N" | "n") echo "Aborting";;
	*) echo "Did not recognize input, aborting."
	esac
fi



